# Generated by Django 5.2.11 on 2026-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaladBarPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_saladbar", "Can view Salad Bar dashboard"),
                    ("can_manage_saladbar", "Can manage tasks and purge queues"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
